# Streamlit secrets configuration
# Add this content to your Streamlit Cloud secrets
[api]
backend_url = "https://agentic-doctor-appointment-system.onrender.com"
request_timeout = 15

[app]
title = "Doctor Appointment System"
description = "AI-powered appointment management with memory chat"