# Streamlit secrets configuration
# Add this content to your Streamlit Cloud secrets
[api]
backend_url = "http://127.0.0.1:8000"
request_timeout = 15

[app]
title = "Doctor Appointment System"
description = "AI-powered appointment management with memory chat"